### PR TITLE
Fire a custom action when authenticating

### PR DESCRIPTION
**Pull request by mjangda**
This will provide a signal for other plugins like Two Factor that the user successfully authenticated via an application password and allow them to take further action.

For example, for users of the Two Factor (or other auth) plugin, you could hook in to the new filter and allow the login while restricting others:

```
add_filter( 'two_factor_user_api_login_enable', function( $enable ) {
    // The request uses an Application Password. Override any API login restrictions in place.
    if ( did_action( 'application_password_did_authenticate' ) ) {
        return true;
    }

    return $enable;
}
```

The example there is a bit simplistic (doesn't validate user ID, for example) but hopefully gets the point across.

### CODE REVIEW

**Comment by mjangda** [comment]
Related:

- https://github.com/WordPress/two-factor/issues/300
- https://github.com/WordPress/application-passwords/issues/91

**Comment by mjangda** [comment]
Without this, sites have to rely on a bit of an awkward hack to restrict API access to just application passwords, e.g.

```
add_action( 'updated_user_meta', function( $meta_id, $user_id, $meta_key, $meta_value ) {
    if ( ! class_exists( 'Application_Passwords' ) ) {
        return;
    }
 
    if ( Application_Passwords::USERMETA_KEY_APPLICATION_PASSWORDS !== $meta_key ) {
        return;
    }
 
    add_filter( 'two_factor_user_api_login_enable', function( $enabled, $api_user_id ) use ( $user_id ) {
        if ( $user_id === $api_user_id ) {
            return true;
        }
 
        return $enabled;
    }, 10, 2 );
}, 10, 4 );
```

**Comment by mjangda** [comment]
@kasparsd Good catch! Done in 355e902

**Comment by flaurus** [comment]
Hey everyone,
thank you all for the great work on this plugin! 

I have a question about this:
Is the main password still intended to work via Api with the filter _add_filter( 'two_factor_user_api_login_enable', '__return_true' );_ added? It does in my case and I don't really understand why I would use the two plugins Two-Factor and Application-Passwords together then?
[As mentioned](https://github.com/WordPress/application-passwords/issues/91#issuecomment-526363133) in #91 

Thanks!

**Pull request merged**
